config/routes.rb
Chalkprototype::Application.routes.draw do
  root to: 'sessions#new'
     
  resources :users 
  resources :questions
  resources :sessions, only: [:new, :create, :destroy]
  resources :message_board
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
    
   
  
  

   match ':controller(/:action(/:id))(.:format)'
   resources :questions
end

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <nav>
      	<ul class = "nav pull-left">
      	<li><%= link_to "Chalk", {:controller => "frontpage", :action => "frontpage"}, :id => "site_title" %></li>
		<% if signed_in?%>
		<li class = "navelement-left"><%=current_user.school_name%></li>
		<% else %>	
		<li class = "navelement-left">schools</li>
		<%end%>
		</ul>
        <ul class="nav pull-right">
			<% if signed_in?%>
          <li class = "navelement-right <%= 'active' if params[:controller] == 'message_board' %>"><%= link_to "chalkboard", 	    {:controller => :message_board, :action => :show}%></li>
            <!-- <li id="fat-menu" class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Submit <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu">
                            <li><%= link_to "Question", :controller => :submission, :action => :QS %></li>
                            <li><%= link_to "Idea",  :controller => :submission, :action => :AS %></li>
                          </ul>
                        </li> -->
			<li  class="dropdown navelement-right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%=current_user.first_name + " " + current_user.last_name%> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu navelement-sub">
                <li>
                  <%= link_to "sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path, :class => "navelement-right" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
 <title><%= @title %></title>

 <%= csrf_meta_tag %>
 <%= javascript_include_tag "application" %>

 <%= stylesheet_link_tag 'application', :media => 'screen' %> 


<script src="http://code.jquery.com/jquery-latest.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js" type="text/javascript"></script>
<script src="http://d3js.org/d3.v2.js"></script>


<script type="text/javascript">

jQuery.fn.submitWithAjax = function() {
  this.live("click", function() {
    $.ajax({type: "GET", url: $(this).attr("href"), dataType: "script"});
    return false;
  });
};

// Here's an example of the class that will be 'clicked'
$(".vote").submitWithAjax();

function add_tag() {
		var tag_input = document.getElementById("tag_editor_input");
		var tag_name = tag_input.value.substring(0,tag_input.value.length-1);
		tag_input.value = "";
		if (tag_name!=""){		
			$("#tag_space").append("<span class = 'tag'><span class='tag_name'>"+tag_name+"</span><a href='#' 	onclick='$(this).parent().remove()'> x</a></span>");
		}
}


$(document).ready(function(){
	prev_length=$("#tag_editor_input").val().length;
	$("#tag_editor_input").keyup(function(event) {
		var unicode=event.charCode? event.charCode : event.keyCode;
		
		//188 is comma
		if (unicode == 188){
			add_tag();
		}
		if (unicode == 8 && prev_length==0){
			$(this).prev().children().last().remove();
		}
		prev_length = $(this).val().length;
     }); 


	$("#question_submit").click(function(event){
		var tags_str = "";
		$(".tag_name").each(function () {
			   if (tags_str == "")
				tags_str = $(this).text();
			  else
				tags_str += ","+$(this).text();
		  });
		$("#tag_names").val(tags_str);	
	});
	
	// Here is the JQuery for Coulton's buttons 
	$("#question_submit, #sign_in_button, .display_all").hover(
	function() {
	$(this).stop().animate({"opacity": "1"}, "fast");
	},
	function() {
	$(this).stop().animate({"opacity": "0.5"}, "fast");
	});
	
	$('#dynamicinput').live('keyup keydown', function(e) {
	  var maxLen = 140;
	  var left = maxLen - $(this).val().length;
	  $('#char-count').html(left);
	});
	
	// JQuery for the Coulton's frontpage tabs
	// $(".tabContents").hide();
	// $(".tabContents:first").show();
	// $("#tabContainer ul li span").click(function(){
	//      var activeTab = $(this).attr("name"); //save the clicked links target
	//      $("#tabContainer ul li span").removeClass("active"); // remove pre-highlighted tabs
	//      $(this).addClass("active"); //set this link to highlight
	//      $(".tabContents").hide(); // again hide pre-showing div
	//      $(activeTab).fadeIn(); //match the target div &amp; show it
	// });
	



});

</script>


</head>
<body>

	<%= render 'layouts/header' %>

	  <% flash.each do |key, value| %>
	  <div class="alert alert-<%= key %>"><%= value %></div>
	  <% end %>
      <%= yield %>

	
	<!--<div id = "footer">chalk&nbsp&nbsp</div>-->

</body>
</html>